apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: workflow-template-hello-world
  annotations:
    argocd.argoproj.io/hook: PostSync
  
spec:
  entrypoint: whalesay-template
  arguments:
    parameters:
      - name: message
        value: "hellloo world..."
  workflowTemplateRef:
    name: workflow-template-submittable
